# Generated by Django 3.1.4 on 2021-01-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plant_observations'),
        ('plantgroup', '0002_auto_20210103_0218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantgroup',
            options={'verbose_name': 'PlantGroup', 'verbose_name_plural': 'PlantGroups'},
        ),
        migrations.RemoveField(
            model_name='plantgroup',
            name='plant',
        ),
        migrations.AddField(
            model_name='plantgroup',
            name='plants',
            field=models.ManyToManyField(to='plants.Plant', verbose_name='Plents'),
        ),
    ]
