# Generated by Django 3.1.4 on 2021-01-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantgroup', '0003_auto_20210103_0227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantgroup',
            options={'verbose_name': 'Plant Group', 'verbose_name_plural': 'Plant Groups'},
        ),
    ]
