# Generated by Django 3.1.4 on 2021-01-03 01:47

import apps.plants.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'plant',
                'verbose_name_plural': 'plants',
            },
        ),
        migrations.CreateModel(
            name='PlantPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.plants.models.get_image_filename, verbose_name='Photos')),
                ('plant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
            options={
                'verbose_name': 'plantphoto',
                'verbose_name_plural': 'plantphotos',
            },
        ),
    ]
