# Generated by Django 3.1.4 on 2021-01-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0002_remove_maintenance_plant_name'),
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='maintenances',
            field=models.ManyToManyField(to='maintenances.Maintenance', verbose_name='Maintenances'),
        ),
    ]
