# Generated by Django 3.1.4 on 2021-01-03 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_maintenances'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'verbose_name': 'Plant', 'verbose_name_plural': 'Plants'},
        ),
        migrations.AlterModelOptions(
            name='plantphoto',
            options={'verbose_name': "Plant's photo", 'verbose_name_plural': "Plant's photos"},
        ),
    ]
