# Generated by Django 3.1.4 on 2021-01-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='plant_name',
        ),
    ]
