# Generated by Django 3.1.4 on 2021-01-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0002_remove_maintenance_plant_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Maintenance', 'verbose_name_plural': 'Maintenances'},
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
